# Generated by Django 4.1.1 on 2022-12-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment_Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('Recruitment_Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recruitment_season')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('total_questions', models.CharField(max_length=100)),
                ('max_marks', models.CharField(max_length=100)),
                ('Round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.round')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_statement', models.CharField(max_length=100)),
                ('answer_type', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
            ],
        ),
    ]
