# Generated by Django 4.1.1 on 2022-12-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_recruitment_season_recruitmentseason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
