# Generated by Django 4.1.1 on 2022-12-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatorpanel',
            old_name='parent_id',
            new_name='panel_id',
        ),
    ]
