# Generated by Django 4.1.1 on 2022-12-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_parent_id_evaluatorpanel_panel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='RecruitmentSeason',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Round',
        ),
    ]
